<!-- Example of an XML document with a DTD -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library [
<!ELEMENT library (book+)>
<!ELEMENT book (title,author,year,isbn)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
]>
<library>
  <book>
    <title>To Kill a Mockingbird</title>
    <author>Harper Lee</author>
    <year>1960</year>
    <isbn>9780446310789</isbn>
  </book>
  <book>
    <title>1984</title>
    <author>George Orwell</author>
    <year>1949</year>
    <isbn>9780451524935</isbn>
  </book>
  <book> 
    <title>Dune</title>
    <author>Frank Herbert</author>
    <year>1964</year>
    <isbn>9780451524975</isbn>
  </book>
</library>